name: Deploy to nekoweb

# only run on changes to main. Use main or master depending on whatever your default branch is called.
on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-nekoweb
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # The checkout step copies your repo into the action runner. Important!
    - uses: actions/checkout@v4
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site
    # If you don't need Node.js to build your site, you can omit this.
    - name: Use PNPM
      uses: pnpm/setup@v2
      with:
        version: 12.0.0
        runtime: node@lts
    # If you have a different build process, replace this with your own build steps
    - name: Install deps and build
      run: pnpm build
    # When the dist_dir is ready, deploy it to neocities
    # Here we deploy the folder named `public`
    - name: Deploy to nekoweb
      uses: indiefellas/deploy2nekoweb@main
      with:
        api_key: ${{ secrets.NEKOWEB_API_TOKEN }}
        nekoweb-domain: ${{ vars.NEKOWEB_DOMAIN }}
        nekoweb-username: ${{ vars.NEKOWEB_USERNAME }}
        directory: 'dist'
